apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb-deployment
spec:
  selector:
    matchLabels:
      app: loansdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - image: mysql:latest
          name: loansdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loansdb-secret
                  key: password
          ports:
            - containerPort: 3306
              name: loansdb
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  ports:
    - port: 3307
  selector:
    app: loansdb